name: rive_dock_tile
description: Rive animation in macOS dock demo
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rive: 0.10.1
  screen_retriever: 0.1.6

dev_dependencies:
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/eye_icon.riv